'use client'

// components/roadmap/RoadmapActions.tsx
// Download PDF and Save for Later actions.
// PDF is a stub — shows a toast instead of crashing.
// TODO: replace stub toast with real file download when backend delivers pdfUrl.

import { useState } from 'react'
import { DownloadIcon, BookmarkIcon, Loader2Icon } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'
import { getRoadmapPdf } from '@/services/roadmapService'
import { cn } from '@/lib/utils'

interface RoadmapActionsProps {
  roadmapId: string
  className?: string
}

export function RoadmapActions({ roadmapId, className }: RoadmapActionsProps) {
  const [pdfLoading, setPdfLoading] = useState(false)
  const [savedLoading, setSavedLoading] = useState(false)

  async function handleDownloadPdf() {
    setPdfLoading(true)
    try {
      const res = await getRoadmapPdf({ roadmapId })
      if (res.error || !res.data) {
        toast.error('Не удалось получить PDF. Попробуйте позже.')
        return
      }
      if (res.data.pdfUrl === '#' || !res.data.pdfUrl) {
        // Stub: PDF not yet generated by backend
        toast.info('PDF будет доступен после интеграции')
        return
      }
      window.open(res.data.pdfUrl, '_blank', 'noopener,noreferrer')
    } finally {
      setPdfLoading(false)
    }
  }

  async function handleSaveLater() {
    setSavedLoading(true)
    try {
      // Stub: copy current URL to clipboard (or show toast if unavailable)
      const url = window.location.origin + '/roadmap/ready'
      await navigator.clipboard.writeText(url).catch(() => {
        // Clipboard may be unavailable; still show success toast
      })
      toast.success('Ссылка скопирована')
    } finally {
      setSavedLoading(false)
    }
  }

  return (
    <div className={cn('flex flex-col gap-3 sm:flex-row', className)}>
      <Button
        size="lg"
        onClick={handleDownloadPdf}
        disabled={pdfLoading}
        className="w-full sm:w-auto"
      >
        {pdfLoading ? (
          <Loader2Icon className="h-4 w-4 animate-spin" aria-hidden="true" />
        ) : (
          <DownloadIcon className="h-4 w-4" aria-hidden="true" />
        )}
        Скачать PDF
      </Button>

      <Button
        variant="outline"
        size="lg"
        onClick={handleSaveLater}
        disabled={savedLoading}
        className="w-full sm:w-auto"
      >
        {savedLoading ? (
          <Loader2Icon className="h-4 w-4 animate-spin" aria-hidden="true" />
        ) : (
          <BookmarkIcon className="h-4 w-4" aria-hidden="true" />
        )}
        Сохранить на потом
      </Button>
    </div>
  )
}
